package co.xingguo.travelmanage.mapper;

import co.xingguo.travelmanage.model.Hotel;
import co.xingguo.travelmanage.model.HotelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    long countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    List<Hotel> selectByExampleWithBLOBsWithRowbounds(HotelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    List<Hotel> selectByExampleWithBLOBs(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    List<Hotel> selectByExampleWithRowbounds(HotelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);
}