package co.xingguo.travelmanage.model;

import java.math.BigDecimal;

public class Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.ID
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.NAME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.CREATOR
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.SCORE
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.ADDRESS
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.PRICE
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.COMMENT_COUNT
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.VIEW_COUNT
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.TAG
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.CTIME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.UTIME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private Long utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL.DESCRIPTION
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.ID
     *
     * @return the value of HOTEL.ID
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.ID
     *
     * @param id the value for HOTEL.ID
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.NAME
     *
     * @return the value of HOTEL.NAME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.NAME
     *
     * @param name the value for HOTEL.NAME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.CREATOR
     *
     * @return the value of HOTEL.CREATOR
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.CREATOR
     *
     * @param creator the value for HOTEL.CREATOR
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.SCORE
     *
     * @return the value of HOTEL.SCORE
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.SCORE
     *
     * @param score the value for HOTEL.SCORE
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.ADDRESS
     *
     * @return the value of HOTEL.ADDRESS
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.ADDRESS
     *
     * @param address the value for HOTEL.ADDRESS
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.PRICE
     *
     * @return the value of HOTEL.PRICE
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.PRICE
     *
     * @param price the value for HOTEL.PRICE
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.COMMENT_COUNT
     *
     * @return the value of HOTEL.COMMENT_COUNT
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.COMMENT_COUNT
     *
     * @param commentCount the value for HOTEL.COMMENT_COUNT
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.VIEW_COUNT
     *
     * @return the value of HOTEL.VIEW_COUNT
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.VIEW_COUNT
     *
     * @param viewCount the value for HOTEL.VIEW_COUNT
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.TAG
     *
     * @return the value of HOTEL.TAG
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.TAG
     *
     * @param tag the value for HOTEL.TAG
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.CTIME
     *
     * @return the value of HOTEL.CTIME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.CTIME
     *
     * @param ctime the value for HOTEL.CTIME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.UTIME
     *
     * @return the value of HOTEL.UTIME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public Long getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.UTIME
     *
     * @param utime the value for HOTEL.UTIME
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setUtime(Long utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL.DESCRIPTION
     *
     * @return the value of HOTEL.DESCRIPTION
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL.DESCRIPTION
     *
     * @param description the value for HOTEL.DESCRIPTION
     *
     * @mbg.generated Wed Apr 22 21:26:51 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}