package co.xingguo.travelmanage.model;

import java.math.BigDecimal;

public class Landscape {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.ID
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.CREATOR
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.TITLE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.OPEN_TIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private String openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.ADDRESS
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.PRICE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.IMG_URL
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.VIEW_COUNT
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.COMMENT_COUNT
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.SCORE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.TAG
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.CTIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.UTIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private Long utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANDSCAPE.DESCRIPTION
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.ID
     *
     * @return the value of LANDSCAPE.ID
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.ID
     *
     * @param id the value for LANDSCAPE.ID
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.CREATOR
     *
     * @return the value of LANDSCAPE.CREATOR
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.CREATOR
     *
     * @param creator the value for LANDSCAPE.CREATOR
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.TITLE
     *
     * @return the value of LANDSCAPE.TITLE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.TITLE
     *
     * @param title the value for LANDSCAPE.TITLE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.OPEN_TIME
     *
     * @return the value of LANDSCAPE.OPEN_TIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.OPEN_TIME
     *
     * @param openTime the value for LANDSCAPE.OPEN_TIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime == null ? null : openTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.ADDRESS
     *
     * @return the value of LANDSCAPE.ADDRESS
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.ADDRESS
     *
     * @param address the value for LANDSCAPE.ADDRESS
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.PRICE
     *
     * @return the value of LANDSCAPE.PRICE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.PRICE
     *
     * @param price the value for LANDSCAPE.PRICE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.IMG_URL
     *
     * @return the value of LANDSCAPE.IMG_URL
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.IMG_URL
     *
     * @param imgUrl the value for LANDSCAPE.IMG_URL
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.VIEW_COUNT
     *
     * @return the value of LANDSCAPE.VIEW_COUNT
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.VIEW_COUNT
     *
     * @param viewCount the value for LANDSCAPE.VIEW_COUNT
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.COMMENT_COUNT
     *
     * @return the value of LANDSCAPE.COMMENT_COUNT
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.COMMENT_COUNT
     *
     * @param commentCount the value for LANDSCAPE.COMMENT_COUNT
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.SCORE
     *
     * @return the value of LANDSCAPE.SCORE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.SCORE
     *
     * @param score the value for LANDSCAPE.SCORE
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.TAG
     *
     * @return the value of LANDSCAPE.TAG
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.TAG
     *
     * @param tag the value for LANDSCAPE.TAG
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.CTIME
     *
     * @return the value of LANDSCAPE.CTIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.CTIME
     *
     * @param ctime the value for LANDSCAPE.CTIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.UTIME
     *
     * @return the value of LANDSCAPE.UTIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public Long getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.UTIME
     *
     * @param utime the value for LANDSCAPE.UTIME
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setUtime(Long utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANDSCAPE.DESCRIPTION
     *
     * @return the value of LANDSCAPE.DESCRIPTION
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANDSCAPE.DESCRIPTION
     *
     * @param description the value for LANDSCAPE.DESCRIPTION
     *
     * @mbg.generated Sun Apr 19 22:17:07 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}